### ISSUE TITLE
Allow for ignoring items

### ISSUE THREAD

**Issue by alex1431999** [alex1431999/Medivialyzer#4]
We should:
- [x] add a button to ignore items to the item list
- [x] add a settings menu where you can see the ignored items

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added an ignore button to LootListItem.vue, created a new SettingsMenu.vue component, and updated App.vue to include the SettingsMenu. Also added necessary logic to handle ignored items.

You can review changes in this commit: https://github.com/mnmnk43434/alex1431999-Medivialyzer-4/commit/3bc3545021110ef7f3aa13eeaa11a3ced88ec7dc.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
